### ISSUE TITLE
lunchable_splitlunch Validation Error

### ISSUE THREAD

**Issue by juftin** [juftin/lunchable-splitlunch#1]
[created via private email]

Unfortunately, importing transactions through the refresh command is not working for me and I was wondering if it is something you are aware of.

I created a splitwise account for testing with one transactiom, here’s the output of the expenses command:

When I run the refresh command, I receive the following error (see attached file for the stack trace): 
![image](https://github.com/juftin/lunchable-splitlunch/assets/49741340/fa66e6f8-3d40-4e73-b390-5c195d47ea04)

**Comment by juftin** [comment]
Full disclosure - I don't actually use Splitwise any more so I'm not always the greatest with updates to `lunchable-splitunch` but this looks straightforward enough that I probably don't need splitwise access anyways

**Comment by juftin** [comment]
👀 looks like the StackTrace is complaining about a [date_from_datetime_inexact](https://docs.pydantic.dev/latest/errors/validation_errors/#date_from_datetime_inexact) error.

**Comment by alexsalomon** [comment]
My guess is that Splitwise is returning a datetime such as `2024-02-26T23:04:06Z` and your script is trying to parse into a date YYYY-MM-DD?

**Comment by juftin** [comment]
I think the issue must be here: https://github.com/juftin/lunchable-splitlunch/blob/d82951c6623f32d6ca960caacce08a39b9002b95/lunchable_splitlunch/lunchmoney_splitwise.py#L953-L959

**Comment by juftin** [comment]
> My guess is that Splitwise is returning a datetime such as `2024-02-26T23:04:06Z` and your script is trying to parse into a date YYYY-MM-DD?

Yeah exactly, I'm passing a `datetime.datetime` object that's incompatible with the `datetime.date` validation that Pydantic is performing.

**Comment by juftin** [comment]
This is also a concerning [error](https://docs.pydantic.dev/2.6/errors/validation_errors/#string_type), I would've thought pydantic would happily coerce that into a string

```
Input should be a valid string [type=string_type, input_value=123456789, input_type=int]
```


**EDIT**,  dang, I was wrong about that one, this raises an error
```py
from pydantic import BaseModel


class Example(BaseModel):
    external_id: str


example = Example(external_id=123)
```

**EDIT 2**:

I'll need to do something like this instead:
```py
from pydantic import BaseModel, field_validator


class Example(BaseModel):
    external_id: str

    @field_validator("external_id", mode="before")
    @classmethod
    def check_external_id(cls, v):
        if v:
            return str(v)


example = Example(external_id=123)
```

**Comment by juftin** [comment]
I think I should have resolved the issue for now 🤞. Here comes the new release. You'll have to uninstall / upgrade `lunchable-splitlunch`

**Comment by juftin** [comment]
Okay @alexsalomon, take a look. `lunchable-splitlunch==1.0.2` was just published

**Comment by alexsalomon** [comment]
Thank you, @juftin! I'll take a look now

**Comment by alexsalomon** [comment]
It seems to have worked, I was just able to import 4xx transactions!! :) 
Thank you very much for the quick reply and action in fixing the issue! 🙏
